name: InOut
description: "A new Flutter project."
publish_to: "none"
version: 0.2.3+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2 # state management
  cached_network_image: ^3.3.1 # cached image
  connectivity_plus: ^2.3.8 # check network
  cookie_jar: ^4.0.8 # allow httponly cookie on mobile
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.10 # data table
  dio: ^5.4.0 # api management
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.5 # json converter
  file_picker: ^6.1.1
  fl_chart: ^0.66.2 # chart
  flutter:
    sdk: flutter
  flutter_background_service: ^4.0.0 # background service
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0 # .env
  flutter_local_notifications: ^16.3.2 # notification
  flutter_osm_plugin: ^0.70.4
  geolocator: ^11.0.0
  get: ^4.6.6 # dependency injection
  get_it: ^7.6.7
  go_router: ^13.2.0 # router
  hive: ^2.2.3 # local database (more secure)
  hive_flutter: ^1.1.0
  home_widget: ^0.4.1 # home widget
  intl: ^0.17.0
  local_auth: ^2.1.8 # biometric
  mobile_scanner: ^3.5.5
  open_filex: ^4.4.0 # open local file
  path_provider: ^2.1.2 # get local file path
  path_provider_android: ^2.2.2
  path_provider_ios: ^2.0.11
  pdf: ^3.10.7 # create pdf
  permission_handler: ^11.2.0 # permission handler
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7 # stream handler (notification)
  shared_preferences: ^2.2.2 # local storage
  syncfusion_flutter_signaturepad: ^24.2.9
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_backgrounnd: "#ffffff"
  adaptive_icon_foregroud: "assets/images/background.png"
